mode = "dark"

accent = "#A6D96A"
selection = "#22301D"
muted = "#7F887A"

background = "#080B0A"
dark_background = "#060806"
darker_background = "#040504"
lighter_background = "#121A14"

foreground = "#E9E5D6"
dark_foreground = "#697268"
light_foreground = "#D9D6C9"
bright_foreground = "#F7F3E7"

hyprland_active_border = "rgba(a6d96aee) rgba(d4b35aee) 38deg"

red = "#DA655E"
yellow = "#D4B35A"
orange = "#C9874B"
green = "#A6D96A"
cyan = "#72B8AE"
blue = "#5D8CEB"
magenta = "#B27B9B"
brown = "#8A6B49"

bright_red = "#ED827B"
bright_yellow = "#E6CA79"
bright_green = "#C0ED88"
bright_cyan = "#91D2C7"
bright_blue = "#82A7F4"
bright_magenta = "#C995B4"
