background = "#0B100D"
background-alpha = 0.99
text = "#E9E5D6"
border = "#354437"
border-alpha = 0.82
scrim = "#040504"
scrim-alpha = 0.62
selected-background = "#A6D96A"
selected-background-alpha = 0.09
selected-text = "#C0ED88"
selected-border = "#A6D96A"
selected-border-alpha = 0.95
selected-border-width = "0 0 0 4"
