background = "#080B0A"
background-alpha = 0.88
text = "#F7F3E7"
placeholder = "#7F887A"
text-error = "#DA655E"
border = "#354437"
border-active = "rgba(a6d96aee) rgba(d4b35aee) 38deg"
border-error = "#DA655E"
border-alpha = 0.96
border-width = "1 1 1 4"
border-active-width = "1 1 1 4"
border-error-width = "1 1 1 4"
selection = "#A6D96A"
selection-alpha = 0.42
